#pragma once

// Copy this file to server_secrets.h and keep the real values local.
// server_secrets.h is ignored by git.

#define VISITESCRIBE_SERVER_BASE_URL "https://scribe.primumnonnocere.olares.com"

// Must match the Device ID configured in the VisiteScribe API admin UI.
#define VISITESCRIBE_DEVICE_ID "visitescribe-cores3-001"

// Paste the device token generated by the API admin UI here.
#define VISITESCRIBE_DEVICE_TOKEN "PASTE_DEVICE_TOKEN_HERE"

// Optional: override VISITESCRIBE_SERVER_CA_PEM here only when the endpoint
// deliberately uses another CA chain. Normally the firmware default is used.
